name: wallpaper_composer
description: Video wallpaper composition app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase for storage
  supabase_flutter: ^2.3.4
  three_dart: ^0.0.16
  flutter_gl: ^0.0.21
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4
  
  # Video playback
  video_player: ^2.8.2
  # File picking
  file_picker: ^6.1.1
  # HTTP requests
  http: ^0.13.6
  # State management
  provider: ^6.1.1
  # UUID generation & animations
  lottie: ^3.0.0
  uuid: ^4.3.3
  # REMOVED: flutter_dotenv (not needed for production)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/login_image.png
    - assets/animations/hello_text.json
    - assets/animations/hello.json
    - assets/animations/loading.json
    - assets/animations/login_computer.json
    - assets/animations/welcome.json
    - assets/animations/next.json
    - assets/animations/flower_loading.json
